name: "fvae"
platform: "pytorch_libtorch"
max_batch_size: 128
input {
    name: "INPUT__0"
    data_type: TYPE_FP32
    dims: 2
  }
output {
    name: "OUTPUT__0"
    data_type: TYPE_FP32
    dims: 28
    dims: 28
  }

